name: Contract Tests
description: Runs Contract Tests (builds, starts service, runs SDK contract test harness)
inputs:
  workspace_path:
    description: 'Path to the package (e.g. lib/sdk/server).'
    required: true
  token:
    description: 'Github token, used for contract tests'
    required: false
    default: ''
  test_harness_params_v2:
    description: 'Optional extra parameters for the SDK test harness v2. Passed as TEST_HARNESS_PARAMS_V2 to make.'
    required: false
    default: ''
  test_harness_params_v3:
    description: 'Optional extra parameters for the SDK test harness v3 (e.g. -enable-long-running-tests). Passed as TEST_HARNESS_PARAMS_V3 to make.'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Run contract tests
      shell: bash
      run: make contract-tests -C ${{ inputs.workspace_path }} TEST_HARNESS_PARAMS_V2="${{ inputs.test_harness_params_v2 }}" TEST_HARNESS_PARAMS_V3="${{ inputs.test_harness_params_v3 }}"
