name: java-sdk-internal

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-test-java-sdk-internal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Shared CI Steps
        uses: ./.github/actions/ci
        with:
          workspace_path: 'lib/shared/internal'
          java_version: 8
