name: java-server-sdk

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  test-platforms-and-versions:
    strategy:
        matrix:
          os: [ubuntu-20.04]
          javaversion: [8, 11, 17, 19]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Shared CI Steps
        uses: ./.github/actions/ci
        with:
          workspace_path: 'lib/sdk/server'
          java_version: ${{ matrix.javaversion }}

  test-contract-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Shared CI Steps
        uses: ./.github/actions/ci
        with:
          workspace_path: 'lib/sdk/server'
          java_version: 8

      - name: Contract Tests
        uses: ./.github/actions/contract-tests
        with:
          workspace_path: 'lib/sdk/server'
          token: ${{ secrets.GITHUB_TOKEN }}

  test-packaging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Shared CI Steps
        uses: ./.github/actions/ci
        with:
          workspace_path: 'lib/sdk/server'
          java_version: 8

      - name: Publish Maven Local
        shell: bash
        run: lib/sdk/server/gradlew publishToMavenLocal -p lib/sdk/server -P skipSigning=true

      - name: Run Packaging Test
        shell: bash
        run: make all -C lib/sdk/server/packaging-test
