name: java-server-sdk-otel

on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-test-java-server-sdk-otel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.1.0
        name: Get secrets
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
          ssm_parameter_pairs: '/production/common/releasing/android_code_signing/private_key_id = SIGNING_KEY_ID'

      - name: Shared CI Steps
        uses: ./.github/actions/ci
        with:
          workspace_path: 'lib/java-server-sdk-otel'
          java_version: 8
